### ISSUE TITLE
Fixes, improvements, refactorings for the compiler and devpack

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#199]
This issue is a collection of bugs and improvements found along the way that should be fixed and applied to the neow3j compiler and devpack.

Included in release 3.2.1:
- [x] Correct byte array instantiation. Simply use the `NEWBUFFER` NeoVM opcode instead of `NEWARRAY` opcode, when a byte array is instantiated. Optimizations for array initializations will be handled in #177 (in release 3.2.1)
- [x] Fix `Helper.toInt()` method and add missing `Helper.asByte()` method to devpack (in release 3.2.1)
- [x] Relational operators for integers work in reverse (in release 3.2.1)
- [x] Accessing a field variable doesn't use the correct owner class of the method (in release 3.2.1)
- [x] Smart contracts without any class-level annotations don't compile because the list of annotation is null (in release 3.2.1)

Included in release 3.3.0:
- [x] The `buildManifestExtra()` method only checks for the `@ManifestExtras` annotation and therefore misses the cases in which the developer only adds one `@ManifestExtra` to the contract class. Resolved in #215. 
- [x] The JVM instruction `DUP2` is not properly converted into NeoVM code, i.e. the produced NeoVM script can be erroneous. Resolved in #218.
- [x] Support the helper methods `addressToScriptHash()`, `hexToBytes()`, `stringToInt()` but without implementing a VM like the `CctorSubVM` from neo-devpack-dotnet. I.e., only support constant value parameters. The methods have been implemented and the compiler extended in #217.

**Comment by csmuller** [comment]
Opened a new issue with the same intent like this one but for milestone 3.4.0. Like this we always know what was done in which milestone, which makes reporting easier.
