### ISSUE TITLE
RC2 Updates

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#537]
Here's the collection of changes from the neo-project repositories that affect neow3j.
It's sorted by the repository and I added the commit in which the change appears.
Not all of these points are in actionable form. For some of them we still need to figure out what we have to change in neow3j to match the changes in neo-core.

**neo**

- [x] 8fe3dbb962c78979b3f2de85ce1499c1510493a2: Changed name of InteropServices System.Crypto.CheckMultisig and System.Crypto.CheckSig. Merged #491 into the rc2 branch.
- [x] df703684235211a771af11a0910519a301e4d8a2, d618d564be94654218f273acf8fb6b0e5055764f: Add new InteropService "System.Runtime.BurnGas".
    - [x] Add to `InteropService` enum and add method in `Runtime`.
    - [x] Write test for `Runtime.burnGas(...)`.
- [x] ebf3f5c7d00ac34b4e6cf39ad4ca74c9e3b1b797: Add new methods to StdLib. Those need to be added to the devpack.
- [x] 73080be7f07f5b47eb69c378323ab7bc73a6d4a6: Remove the NameService native contract wrapper. Devpack doesn't have a NameService contract  interface yet.
    - [x] Change SDK's `NameService` wrapper class to a non-native wrapper.
- [x] eed90873be1822d640b4df3812fc77a56fa97de1: Remove the "System.Iterator.Create" interopService
- [x] 7e2d435aada96e7e22c7564984bff1419377c33f: Add the property "features" to the contract manfiest. Adding a feature annotation to the devpack is handeld separately in #539.
- [x] 4d45a796e9bb0e3427ddee56a626b4b8f27f3e16: Add the "Refuel" method to the GasToken contract (SDK and devpack).
    - [x] Add `refuel` method to `GasToken`.
    - [x] Write test for `refuel` method.
- [x] 859133ac44f3f8db8afae69c38289a376eaa0e71: MAX_VALID_UNTIL_BLOCK_INCREMENT is now a protocol setting. How will we retrieve the value?

**neo-modules**

- [x] a465c0a2c256c02ae8152f7cd1c6a9d04dcf32fd: In NeoGetVersion change the "Magic" field to "Network" ("network). There is an issue on this #518.
- [x] 4359882d2b72838ad915f0d5ead0322589c4f443: Add a MaxIteratorResultItems to the RpcServer config.
- [x] Fix RPC getstateroot witnesses. The entry `witness` in the response was changed to `witnesses` as an array.

**neo-vm, neo-node, neo-devpack**

No directly affecting changes.
The neo-devpack has a lot of changes because Eric reworked the compiler. I did not go through all the changes.

**Comment by gsmachado** [comment]
This is done through #538. Great work! 💪
