### ISSUE TITLE
Support creation and import of NeowJava libraries

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#617]
**Rational**
Developers often rewrite the same functionality. Smart contract coding is no different in this aspect. Therefore, packaging frequently used functionality into libraries and making them available through a build tool is of value. To ensure the integrity and authenticity of such libraries, there needs to be a validation step taking place when the build tool downloads the dependency.

**Tasks**
Gradle, the build tool used to run the neow3j compiler, supports signature and checksum verification if activated in a project.
- [ ] Make sure that the neow3j gradle task and compiler can deal with libraries other then the devpack itself.
- [ ] Check and document the necessary steps to activate dependency verification. (Choose a suitable artifacts repository.)
- [ ] Check and document the necessary steps to publish a verifiable library. (Choose a suitable artifacts repository.)
